[tool.poetry]
name = "reddit-bot"
version = "0.1.0"
description = ""
authors = ["laraib_sidd <laraib.sidd7@gmail.com>"]
readme = "README.md"
packages = [{include = "reddit_bot"}]

[tool.poetry.dependencies]
python = "3.11.5"
pytz = "^2023.3.post1"
firebase-admin = "^6.2.0"
pymongo = "^4.6.0"
praw = "^7.7.1"
python-telegram = "^0.18.0"
python-telegram-bot = "13.13"
aiogram = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
my-telegram-bot = "bot:main"

