name: Send Telegram Messages

# 'on' is the trigger, in this case this Action will
# be triggered using cron set at a 10 minutes interval.
on:
  schedule:
    - cron: "*/15 * * * *"

# 'jobs' are the routines, we only have
# one when the instance is built.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3

    - name: Set up Environment
      uses: ./.github/actions/setup_py_env

    - name: Linting check
      run: |
        echo "Sending messsages to Telegram...."
        poetry run python3 bot.py
