name: Send Telegram Messages

# 'on' is the trigger, in this case this Action will
# be triggered using cron set at a 10 minutes interval.
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
# 'jobs' are the routines, we only have
# one when the instance is built.
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_USER: ${{ secrets.MONGO_DB_NAME }}
      SUB_NAMES: ${{ secrets.SUB_NAMES }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    

    steps:  
    - uses: actions/checkout@v3

    - name: Set up Environment
      uses: ./.github/actions/setup_py_env

    - name: Linting check
      run: |
        echo "Sending messsages to Telegram...."
        poetry run python3 lib/test.py
