name: Send Telegram Messages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3

    - name: Print GitHub Token
      run: |
        echo "The value of GITHUB_TOKEN is: $GITHUB_TOKEN"

    - name: Print Test Environment Variable
      run: |
        echo "The value of TEST_ENV_VAR is: ${{ vars.TEST_ENV_VAR }}"
